# Generated by Django 3.1 on 2022-10-28 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20221028_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='corporate_data_vending_medium',
            field=models.CharField(blank=True, choices=[('MSORG_DEVELOPED_WEBSITE_2', 'MSORG Developed Website 2'), ('UWS', 'UWS'), ('SIMHOST', 'USSD.SIMHOSTING'), ('SIMHOST_NG', 'SIMHOSTNG.COM'), ('QTopUp', 'QTopUp'), ('MSORG_DEVELOPED_WEBSITE', 'MSORG Developed Website 1'), ('SMEPLUG', 'SMEPLUG'), ('EMAIL', 'EMAIL'), ('SMS', 'SMS'), ('MSORG_DEVELOPED_WEBSITE_3', 'MSORG Developed Website 3'), ('SMEIFY', 'SMEIFY')], max_length=30, null=True),
        ),
    ]
